# docker-compose.yml
# -----------------------------------------------------------------------------
# Define a stack para ser implantada no Portainer.
# -----------------------------------------------------------------------------
version: '3.8'

services:
  # Nome do nosso serviço/container
  excel-converter:
    # Imagem pré-construída do Docker Hub
    image: leonardofurlan/excel-converter-app:latest
    container_name: excel-converter-app
    restart: unless-stopped
    
    # <-- AJUSTE ADICIONADO AQUI
    # Define uma verificação de saúde explícita para garantir que o container não seja reiniciado incorretamente.
    # Ela verifica se a aplicação web está respondendo na porta 8000 a cada 30 segundos.
    healthcheck:
      test: ["CMD", "python", "-c", "import sys, urllib.request; sys.exit(0) if urllib.request.urlopen('http://localhost:8000/').getcode() == 200 else sys.exit(1)"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

    networks:
      # Conecta o container à rede externa do Traefik
      - traefik-public
    labels:
      # --- Configuração do Traefik ---
      - "traefik.enable=true"
      - "traefik.constraint-label=traefik-public"
      - "traefik.docker.network=traefik-public"

      # --- Roteamento HTTPS ---
      - "traefik.http.routers.excel-converter.rule=Host(`jse.atospd.com`)"
      - "traefik.http.routers.excel-converter.entrypoints=https"
      - "traefik.http.routers.excel-converter.tls=true"
      - "traefik.http.routers.excel-converter.tls.certresolver=le"
      
      # --- Roteamento HTTP com redirecionamento ---
      - "traefik.http.routers.excel-converter-http.rule=Host(`jse.atospd.com`)"
      - "traefik.http.routers.excel-converter-http.entrypoints=http"
      - "traefik.http.routers.excel-converter-http.middlewares=https-redirect" 

      # --- Serviço ---
      - "traefik.http.services.excel-converter.loadbalancer.server.port=8000"

networks:
  # Declara que 'traefik-public' é uma rede pré-existente no Docker/Portainer
  traefik-public:
    external: true
