# docker-compose.yml
# -----------------------------------------------------------------------------
# Define a stack para ser implantada no Portainer.
# -----------------------------------------------------------------------------
version: '3.8'

services:
  # Nome do nosso serviço/container
  excel-converter:
    # Imagem pré-construída do Docker Hub
    image: leonardofurlan/excel-converter-app:latest
    container_name: excel-converter-app
    restart: unless-stopped
    networks:
      # Conecta o container à rede externa do Traefik
      - traefik-public
    labels:
      # --- Configuração do Traefik ---
      - "traefik.enable=true"
      - "traefik.constraint-label=traefik-public"
      - "traefik.docker.network=traefik-public"

      # --- Roteamento HTTPS ---
      - "traefik.http.routers.excel-converter.rule=Host(`jse.atospd.com`)"
      - "traefik.http.routers.excel-converter.entrypoints=https"
      - "traefik.http.routers.excel-converter.tls=true"
      - "traefik.http.routers.excel-converter.tls.certresolver=le"
      
      # --- Roteamento HTTP com redirecionamento ---
      - "traefik.http.routers.excel-converter-http.rule=Host(`jse.atospd.com`)"
      - "traefik.http.routers.excel-converter-http.entrypoints=http"
      # CORREÇÃO: Removido o 'p' extra do nome do middleware
      - "traefik.http.routers.excel-converter-http.middlewares=https-redirect" 

      # --- Serviço ---
      # CORREÇÃO: A porta interna do container é 8000, não 80.
      - "traefik.http.services.excel-converter.loadbalancer.server.port=8000"

networks:
  # Declara que 'traefik-public' é uma rede pré-existente no Docker/Portainer
  traefik-public:
    external: true
