# docker-compose.yml
# -----------------------------------------------------------------------------
# Versão modificada para usar uma imagem pré-construída do Docker Hub.
# -----------------------------------------------------------------------------
version: '3.8'

services:
  excel-converter:
    image: leonardofurlan/excel-converter-app:latest
    container_name: excel-converter-app
    restart: unless-stopped
    networks:
      - traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.excel-converter.rule=Host(`jse.atospd.com`)"
      - "traefik.http.routers.excel-converter.entrypoints=websecure"
      - "traefik.http.services.excel-converter.loadbalancer.server.port=8000"
      - "traefik.http.routers.excel-converter.tls.certresolver=le"

networks:
  traefik-public:
    external: true
