# docker-compose.yml
# -----------------------------------------------------------------------------
# Versão modificada para usar uma imagem pré-construída do Docker Hub.
# -----------------------------------------------------------------------------
version: '3.8'

services:
  excel-converter:
    image: leonardofurlan/excel-converter-app:latest
    container_name: excel-converter-app
    restart: unless-stopped
    networks:
      - traefik-public
    labels:
      # >>>>> labels obrigatórias para o Traefik enxergar
      - traefik.enable=true
      - traefik.constraint-label=traefik-public
      - traefik.docker.network=traefik-public

      # >>>>> roteamento HTTPS
      - traefik.http.routers.excel-converter.rule=Host(`jse.atospd.com`)
      - traefik.http.routers.excel-converter.entrypoints=https
      - traefik.http.routers.excel-converter.tls=true
      - traefik.http.routers.excel-converter.tls.certresolver=le
      - traefik.http.routers.excel-converter-http.rule=Host(`jse.atospd.com`)
      - traefik.http.routers.excel-converter-http.entrypoints=http
      - traefik.http.routers.excel-converterp-http.middlewares=https-redirect 

      # Porta onde o Apache/PHP escuta DENTRO do container
      - traefik.http.services.excel-converter.loadbalancer.server.port=80

networks:
  traefik-public:
    external: true
